package org.edgexfoundry.rules;
global org.edgexfoundry.service.DistributionCoordinator coordinator;
global org.edgexfoundry.support.logging.client.EdgeXLogger logger;
import org.edgexfoundry.domain.core.Event;
import org.edgexfoundry.domain.core.Reading;
import java.util.Map
import org.edgexfoundry.domain.Channel;
rule "${ruleName}"
when
  $e:Event($rlist: readings && device=="${condDevice}")
  <#if valueChecks??>
  <#assign idx = 0>
  <#list valueChecks as valueCheck>
  $r${idx}:Reading(name=="${valueCheck.parameter}" && ${valueCheck.operand1} ${valueCheck.operation} ${valueCheck.operand2}) from $rlist
    <#assign idx = idx + 1>
  </#list>
  </#if>
then
  coordinator.distribute("${destination}");
  logger.info("${log}");
end