package org.edgexfoundry.rules;
global org.edgexfoundry.service.CommandExecutor executor;
global org.edgexfoundry.support.logging.client.EdgeXLogger logger;
import org.edgexfoundry.domain.core.Event;
import org.edgexfoundry.domain.core.Reading;
import java.util.Map;
rule "${ruleName}"
when
  $e:Event($rlist: readings && device=="${condDevice}")
  <#if valueChecks??>
  <#assign idx = 0>
  <#list valueChecks as valuecheck>
  $r${idx}:Reading(name=="${valuecheck.parameter}" && ${valuecheck.operand1} ${valuecheck.operation} ${valuecheck.operand2}) from $rlist
    <#assign idx = idx + 1>
  </#list>
  </#if>
then
executor.SendTo("${receiver}", "${contentType}", "${content}");
logger.info("${log}");
end