package org.edgexfoundry.rules;
global org.edgexfoundry.service.CommandExecutor executor;
global org.edgexfoundry.support.logging.client.EdgeXLogger logger;
import org.edgexfoundry.domain.core.Event;
import org.edgexfoundry.domain.core.Reading;
import java.util.Map;
rule "${ruleName}"
when
  $e:Event($rlist: readings && device=="${condDeviceId}")
  <#if valuechecks??>
  <#assign idx = 0>
  <#list valuechecks as valuecheck>
  $r${idx}:Reading(name=="${valueCheck.parameter}" && ${valueCheck.operand1} ${valueCheck.operation} ${valueCheck.operand2}) from $rlist
    <#assign idx = idx + 1>
  </#list>
  </#if>
then
executor.SendTo("${reveiver}", "${contextType}", "${content}");
logger.info("${log}");
end